server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/lecture
    username: lecture
    password: 1111

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true